# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

jaytch:
  title: Jaytch!             # Your blog or site title.
  tagline: The Jekyll Helper # Your blog or site tagline.
  page_links: [
    "Blog &amp; News|/blog/",
    "About|/about/",
    "Contributors|/contributors/",
    [ "Documentation", # dropdown label
      # dropdown menu items:
      "Create a Blog in 5 Minutes|/docs/create-a-blog-in-5-minutes/",
      "Hosting on GitHub Pages|/docs/hosting-on-github-pages/",
      "Using Author Bios|/docs/using-author-bios/",
      "Layouts vs. Themes|/docs/layouts-vs-themes/",
      "---",
      "Frequently Asked Questions|/docs/faqs/"
    ]
  ]
  layout:
    name: bootstrap-v3    # default | bootstrap-v3
    minified: true        # Use *.min.css and *.min.js, when available.
    usecdn: false         # Use CDN (content delivery network), when supported.
    customcss: custom.css # loaded after theme css files
    customjs:  custom.js  # loaded after theme js files
    theme: cosmo        # When used by bootstrap-v3, valid values are:
                          #    none | default | cerulean | cosmo | cyborg |
                          #    darkly | flatly | journal | lumen | paper |
                          #    readable | sandstone | simplex | slate |
                          #    spacelab | superhero | united | yeti
  authors:
    groundh0g:
      name:       Joseph Hall
      alias:      groundh0g
      image:      images/groundh0g.png
      role:       Programmer / Writer
      bio: > # brief description goes here
        Joe lives with his wife and three daughters in Newnan, Georgia. Every
        summer, Joe teaches high school students how to write games during an
        intense weeklong course in North Carolina for Landry Academy. In his free
        time, Joe dabbles in sketching, cartooning, and creating 3D models. When
        you see his artistic creations, you’ll understand why he makes his living
        as a programmer.
      email:      hello@codetopia.com
      website:    http://codetopia.com/
      twitter:    groundh0g
      facebook:   groundh0g
      youtube:    groundh0g
      instagram:  groundh0g72
      googleplus: groundh0g
      github:     groundh0g
      deviant:    groundh0g
      linkedin:   groundh0g
    plusjade:
      name:       Jade Dominguez
      alias:      plusjade
      image:      images/plusjade.jpg
      role:       Programmer
      bio: > # brief description goes here
        I owe everything I know to the Open Source community so all my work is
        Open and Free. My most popular project and claim to baby fame is
        JekyllBootstrap which ironically has the least amount of actual code than
        any of my other projects; a testament to the importance of being user and
        usability driven.
      email:      plusjade@gmail.com
      website:    http://plusjade.com/
      twitter:    plusjade
      github:     plusjade